services:
  db:
    image: postgres:17
    environment:
    # Can change user name and pw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fuelpass
    ports:
    # TCP port for postgres
      - "5432:5432"
    volumes:
      - fuelpass-db-data:/var/lib/postgresql/data

volumes:
  fuelpass-db-data:
